name: CI

on: [push]

jobs:
  sast_scan:
     name: Run Bandit Scan
     runs-on: ubuntu-latest
     steps:
     - name: Check out
       uses: actions/checkout@v2
       
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: v3.11
     - name: Install bandit
       run: pip install bandit
     - name: run bandit
       run: bandit -ll -ii -r . -f json -o bandit-findings.json

     - name: Upload findings
       uses: actions/upload-artifact@v7.0.1
       if: always()
       with:
          name: bandit findings
          path: bandit-findings.json
        
  image_scan:
     name: Build image and Scan
     runs-on: ubuntu-latest
     steps: 
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
           
      - name: Build Docker image
        run: docker build -f Dockerfile -t mypygoat:lastest .
        
      - name: Docker Scout Scan
        uses: docker/scout-action@v1.20.4
        with:
           dockerhub-user: ${{ secrets.REPO_USER }}
           dockerhub-password: ${{ secrets.REPO_PWD }}
           command: quickview,cves
           only-severities: critical,high
           sarif-file: scout-report.sarif


      
            
